### ISSUE TITLE
RFE: Allow filtering of erratum type for the api/v1/updates endpoint

### ISSUE THREAD

**Issue by omaciel** [RedHatInsights/vmaas#114]
One should be able to request for a specific erratum type when POSTing to api/v1/updates endpoint. The attribute could be called `erratum_type` and it should take a list of strings.

If the list is empty or not provided, then only security-related erratum should be returned.

**Comment by ggainey** [comment]
I'm going to close this as WONTFIX. VMaaS is a microservice designed to give information about *security vulnerabilities*. If you want more than that, you can get it from ET, or Pulp, or directly from Bugzilla - this service is not a replacement for any of those systems.

**Comment by omaciel** [comment]
Makes sense @ggainey :)
