### ISSUE TITLE
Add Sphinx documentation

### ISSUE THREAD

**Issue by omaciel** [RedHatInsights/vmaas#117]
Even though there is a [wiki](https://github.com/RedHatInsights/vmaas/wiki) already for this project, I feel that using `Sphinx` generated documentation for how to install, how to use it (info already on `README` page), and the endpoints (examples of what to pass and what gets returned).

I'd also add some type of rule (i.e. linting) to make sure that docs are checked before PRs get merged to ensure that we keep them up to date.

**Comment by jdobes** [comment]
We don't plan to support Sphinx documentation. Let's use GH wiki for documenting things and Swagger UI as part of the application itself to provide API endpoints doc.
