### ISSUE TITLE
non ascii characters cause 400 response

### ISSUE THREAD

**Issue by tkasparek** [RedHatInsights/vmaas#148]
non ascii characters in the input break the output vmaas returns 400 instead of meaningful reponse as for
`curl http://webapp-vmaas-stable.1b13.insights.openshiftapps.com/api/v1/updates/baŠ-4.3.42-5.fc23.x86_64` I'd expect `{"update_list": {"baŠ-4.3.42-5.fc23.x86_64": []}}` but instead of it I am getting:
<html><body><h1>400 Bad request</h1>
Your browser sent an invalid request.
</body></html>

**Comment by tkasparek** [comment]
Also `curl -d @vmaas-input.json -X POST http://webapp-vmaas-stable.1b13.insights.openshiftapps.com/api/v1/updates/` with `{
  "package_list" : [
    "baŠ-4.3.42-5.fc23.x86_64"
  ]
}`is broken.

**Comment by grinrag** [comment]
Curl request returns '400 Error: malformed input JSON', so it's not broken, maybe not so informative.
Red Hat released packages cannot contain non-ascii chars, so our regexp for matching URL is "/api/v1/updates/[a-zA-Z0-9-._:]+". We are not going to do the additional work, like parsing NEVRA, make DB requests and only then return error or an empty result, if it is possible to avoid it.

**Comment by grinrag** [comment]
WONTFIX
