### ISSUE TITLE
updates: Missing updates when using rpm name w/o epochnum

### ISSUE THREAD

**Issue by psegedy** [RedHatInsights/vmaas#164]
I have same set of rpms with and without epochnum
```
➜  VMaaS wc -l rpms-64 
626 rpms-64
➜  VMaaS wc -l rpms-64-wo-epoch 
626 rpms-64-wo-epoch
```
But I get differnet number of updates for these two sets
```
➜  VMaaS curl -d @rpms-64 'http://127.0.0.1:8080/api/v1/updates/' | python -m json.tool > updates_for_el64 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  420k    0  393k  100 27498   393k  27498  0:00:01  0:00:01 --:--:--  304k
➜  VMaaS wc -l updates_for_el64                                                                           
14505 updates_for_el64


➜  VMaaS curl -d @rpms-64-wo-epoch 'http://127.0.0.1:8080/api/v1/updates/' | python -m json.tool > updates_for_el64-wo-epoch 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  345k    0  319k  100 26234   319k  26234  0:00:01  0:00:01 --:--:--  273k
➜  VMaaS wc -l updates_for_el64-wo-epoch                                                                                    
11922 updates_for_el64-wo-epoch
```

For example there is difference for `vim-minimal-2:7.2.411-1.8.el6.x86_64` and `vim-minimal-7.2.411-1.8.el6.x86_64`
```json
➜  VMaaS curl 'http://127.0.0.1:8080/api/v1/updates/vim-minimal-2:7.2.411-1.8.el6.x86_64' | python -m json.tool             
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   622    0   622    0     0    622      0 --:--:-- --:--:-- --:--:-- 17771
{
    "update_list": {
        "vim-minimal-2:7.2.411-1.8.el6.x86_64": [
            {
                "erratum": "RHSA-2016:2972",
                "package": "vim-minimal-2:7.4.629-5.el6_8.1.x86_64",
                "repository": "rhel-6-server-rpms__6_DOT_9__x86_64"
            },
            {
                "erratum": "RHSA-2016:2972",
                "package": "vim-minimal-2:7.4.629-5.el6_8.1.x86_64",
                "repository": "rhel-6-workstation-rpms__6Workstation__x86_64"
            },
            {
                "erratum": "RHSA-2016:2972",
                "package": "vim-minimal-2:7.4.629-5.el6_8.1.x86_64",
                "repository": "rhel-6-workstation-rpms__6_DOT_9__x86_64"
            },
            {
                "erratum": "RHSA-2016:2972",
                "package": "vim-minimal-2:7.4.629-5.el6_8.1.x86_64",
                "repository": "rhel-6-server-rpms__6Server__x86_64"
            }
        ]
    }
}


➜  VMaaS curl 'http://127.0.0.1:8080/api/v1/updates/vim-minimal-7.2.411-1.8.el6.x86_64' | python -m json.tool 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    59    0    59    0     0     59      0 --:--:-- --:--:-- --:--:-- 59000
{
    "update_list": {
        "vim-minimal-7.2.411-1.8.el6.x86_64": []
    }
}

```

**Comment by jdobes** [comment]
The current behavior is to evaluate unspecified epoch as epoch 0, in this case vim-minimal with epoch 2 is found but vim-minimal with epoch 0 is not so this result is totally expected by me. How would you handle case when there are both `vim-minimal-2:7.2.411-1.8.el6.x86_64` and `vim-minimal-0:7.2.411-1.8.el6.x86_64` in DB and you ask for updates of `vim-minimal-7.2.411-1.8.el6.x86_64`?

**Comment by psegedy** [comment]
Firstly, I'm sorry, I don't know how exactly epoch is used, so my assumption could be absolutely wrong.


Let say we want to update `vim-minimal-0:7.2.411-1.8.el6.x86_64` and in DB we have `vim-minimal-2:7.4.629-5.el6_8.1.x86_64`, because package with `epoch=2` is always greater, then IMO first package should be upgraded with second one. 

In case when epoch is not specified and thus epoch is evaluated to 0, I think that it is correct to upgrade this package with package with the greatest NEVRA and not with the package with greatest NVRA and equal epoch.

I found on https://fedoraproject.org/wiki/Packaging:Versioning
> The Epoch: tag, which provides the most significant input to RPM's version comparison function, SHOULD ONLY be used or incremented when necessary to avoid ordering issues. If present, it MUST contain a positive integer. **Epoch: MUST NOT ever be decreased in any way**.

according to this I assume that there _should not_ be the case when there exist newer package with older epoch.

In @jdobes case I would return updates for `vim-minimal-2:7.2.411-1.8.el6.x86_64`

**Comment by MichaelMraka** [comment]
@psegedy: true, epoch works the same way as version or release - "the higher is the better".
Actually what you see is a different "issue" - we don't display updates for packages not in database.
And ```vim-minimal-0:...``` is not.

**Comment by grinrag** [comment]
According to the comprehensive answers given above, I'm closing the issue.
