### ISSUE TITLE
Setup proper linking between containers

### ISSUE THREAD

**Issue by jdobes** [RedHatInsights/vmaas#17]
In reposcan README is specified to use --link option to connect with DB container. This option is deprecated and should be replaced with some better system.

**Comment by grinrag** [comment]
@jdobes we are in the process of implementing docker-compose to setup dependencies between containers. 
BTW, where did you find the '--link' is deprecated?

I see `docker create --help`

Options:
...
--link value                  Add link to another container (default [])
...

Docker version 1.12.6, build ec8512b/1.12.6

**Comment by jdobes** [comment]
@grinrag https://docs.docker.com/network/links/

**Comment by grinrag** [comment]
Fixed in PR #46 and PR #53
