### ISSUE TITLE
reposcan: psycopg 2.5 VS psycopg 2.7

### ISSUE THREAD

**Issue by grinrag** [RedHatInsights/vmaas#216]
This is related to the #54 issue. CentOS/RHEL 7 has psycopg version 2.5 which is not supported `execute_values`, so we need to rewrite and test all these statements. One of possible way described here https://stackoverflow.com/questions/8134602/psycopg2-insert-multiple-rows-with-one-query#10147451.

**Comment by jdobes** [comment]
Or eventually base on Python 3 version of CentOS/RHEL image (https://www.softwarecollections.org/en/scls/rhscl/rh-python36/) - they have 2.7 but some libs as requests are missing and need to be rebuilt

**Comment by MichaelMraka** [comment]
Actually we already moved to python3 for reposcan so I'm closing this issue.
