### ISSUE TITLE
reposcan: support more download options

### ISSUE THREAD

**Issue by jdobes** [RedHatInsights/vmaas#24]
Now only download using HTTP is supported, support also HTTPS including client certificates, proxy, etc.

**Comment by tlestach** [comment]
@jdobes, I guess we support HTTPS (at least partly) as we access public CDN. Can you please update, what is still missing here?

**Comment by jdobes** [comment]
The main reason to create this issue was missing HTTPS support and it was fixed already. Although, it's always good to support HTTP proxies, password protected repos etc. I think it's not needed now and can easily be extended if necessary, we use requests library and it should be enough to just pass parameters. Closing the issue.
