### ISSUE TITLE
getaddrinfo EAI_AGAIN webapp-vmaas-stable

### ISSUE THREAD

**Issue by jharting** [RedHatInsights/vmaas#250]
Calling the VMaaS API from Insights we observe the following

`"Error: getaddrinfo EAI_AGAIN webapp-vmaas-stable.1b13.insights.openshiftapps.com:80`

couple of times a day. Looks like a DNS lookup fails. It's not clear at all whether this is a fault at VMaaS side, Insights side or somewhere else (e.g. OpenShift). Filing the issue here for now but may need to be moved later when the investigation begins.

**Comment by ggainey** [comment]
This can't be vmaas or insights - it's a networking-level error, that a DNS lookup failed. I don't see any reason to have an issue open here, there's not going to be a way to 'move it' to wherever the (apparently transient) problem was.
