### ISSUE TITLE
500s on invalid request body

### ISSUE THREAD

**Issue by jharting** [RedHatInsights/vmaas#252]
```
curl -v http://webapp-vmaas-stable.1b13.insights.openshiftapps.com/api/v1/updates -X POST -d '{}'
```
should result in 400. Currently it causes 500.

Related to https://github.com/RedHatInsights/insights-api/issues/207

**Comment by ggainey** [comment]
Well, the python-json-schema validators I've found are only available to openstack/openshit repos on rhel, or not available to rhel at all. Need to decide about the best way to do validation for our (admittedly-pretty-simple) JSON inputs - nab python-jsonschema from the OS/OStack repos, add python-schema to our COPR and use it, find some other json-validator I have missed, or commit some blecherous ad-hockery to do the minimal. Investigation continues.
