### ISSUE TITLE
join_packagename() needed by both webapp and reposcan

### ISSUE THREAD

**Issue by eherget** [RedHatInsights/vmaas#295]
I have cut-n-pasted the join_packagename() method from webapp/utils.py to reposcan/common/package_utils.py when updating the errata api to support Phase II design.  This should possibly be move to a utils or lib that gets used by both webapp and reposcan, however no such thing is currently in place.

**Comment by MichaelMraka** [comment]
I was able to find two possible solutions:
a) build shared code into rpm which will be then installed in both containers - this is nice and clean for production but complicated for development,
b) build a container image with shared code, which will be then used as a base container for the other two containers - unfortunately docker-compose does not support dependencies in image building which makes it again dificult for development.
So for now I'd rather keep duplicate copies of the code.

**Comment by eherget** [comment]
Since it is currently just a single method that would be copied to 2 places, I'm ok with having the 2 copies (with comments in each pointing to the other so updates go both places).

However, if we figure a good plan for this, it would be nice to put some other stuff, common to both webapp and reposcan, into a shared lib/util.  For example, the reposcan/exporter.py defines the order of values that get stored for data objects (cve, errata, etc), but the constants defining the index of these values is in webapp/cache.py.

as a third option, could we put the common sources in a "shared" directory under the vmaas dir (peer to webapp and reposcan dirs) and have the dockerfile in each ADD ../shared to [webapp|reposcan]/shared ?  Or softlink [webapp|reposcan]/shared to ../shared?  The latter likely would work with run_test.sh.

**Comment by MichaelMraka** [comment]
> as a third option, could we put the common sources in a "shared" directory under the vmaas dir (peer to webapp and reposcan dirs) and have the dockerfile in each ADD ../shared to [webapp|reposcan]/shared ? Or softlink [webapp|reposcan]/shared to ../shared? The latter likely would work with run_test.sh.

Both solution you mention (../shared and softlink) do not work in docker ;).
That's why proposed solutions in comment 1 are so complicated.

**Comment by eherget** [comment]
Before PR #294 was accepted, I updated it to build the packagename in the webapp, thus removing the need to duplicate join_packagename() in webapp and reposcan.  This Issue is closed.
