### ISSUE TITLE
  KeyError for "errata_list": [""]

### ISSUE THREAD

**Issue by psegedy** [RedHatInsights/vmaas#326]
```zsh
(.vmaas_venv) ➜  vmaas_tests git:(missing_tests) ✗ cat errata_list.json 
{"errata_list": [""]}
(.vmaas_venv) ➜  vmaas_tests git:(missing_tests) ✗ curl -d @errata_list.json http://localhost:8080/api/v1/errata
Unexpected error: <class 'KeyError'> - 31869%        
```
On server side
```zsh
vmaas-webapp | Unexpected error: <class 'KeyError'> - 31869
vmaas-webapp | ERROR:tornado.access:500 POST /api/v1/errata (172.18.0.1) 18.21ms
```

Similar request for CVEs API works and respond with empty response, so I expect it should behave in the same way

**Comment by tkasparek** [comment]
KeyError was fixed by 6c86d4d3fbf13803cb7b2a26f7d74a3ab15d6347
However there are still some issues regarding returning all erratas, instead of empty output like CVEs API.
Will work on that.
