### ISSUE TITLE
updates API: HTTP 200 and no error is return in case of error in GET request

### ISSUE THREAD

**Issue by jdobes** [RedHatInsights/vmaas#367]
there is an incomplete try-except block in GET handler, use the same exception handling as for POST reqs, implement once in common function

**Comment by psegedy** [comment]
I would like to add this to tests. Do you have any example of such request?
Thanks.

**Comment by jdobes** [comment]
I was able to see it while working on #365 . Should be reproducible with any Internal server error in updates API - but I'm not aware of any right now.

**Comment by Michael-Jurek** [comment]
https://github.com/RedHatInsights/vmaas/pull/537

**Comment by tkasparek** [comment]
Closed via #537
