### ISSUE TITLE
redundant logging in OS environment

### ISSUE THREAD

**Issue by tlestach** [RedHatInsights/vmaas#376]
reposcan logs in the following way:
message	is:
     reposcan-2-stppn 2018-07-30 08:11:45,006 __main__: [INFO] Starting (version latest).

while this is great info for running local docker, not that great for running in OS environment, where all this info is available (e.g. kibana)

the request is not to log pod name and timestamp when running in OS env

**Comment by ggainey** [comment]
This is because in -ci the LOGGING_TYPE env-var is set to DEVEL instead of OPENSHIFT - looks like an issue w/the way the OS images are set up.

**Comment by tlestach** [comment]
Cannot we set LOGGING_TYPE according to the environment variables? I guess based of them we can find out, whether the container runs in docker or in OS.

**Comment by jdobes** [comment]
LOGGING_TYPE itself is an environment variable and should be overriden during OpenShift deployment.

**Comment by jdobes** [comment]
this was already fixed to match current expectations, closing
