### ISSUE TITLE
API: fix way of passing input data in POST request.

### ISSUE THREAD

**Issue by grinrag** [RedHatInsights/vmaas#39]
Now we are expecting to receive an input data as a json file attached to POST request. We also should expect to receive data as a body of POST request.

**Comment by jdobes** [comment]
Isn't enough to support only receiving it as body (not as a file)?

For example curl should can load the file as body too:

`curl -d  '{"key1":"value1", "key2":"value2"}' -H "Content-Type: application/json" -X POST http://<FQDN>:8080/api/v1/json/`

`curl -d "@data.json" -H "Content-Type: application/json" -X POST http://<FQDN>:8080/api/v1/json/`

**Comment by grinrag** [comment]
Maybe it's enough, but now we support input data as a file only. So anyway we need to implement the second way.

**Comment by jdobes** [comment]
Merged.
