### ISSUE TITLE
add api to reposcan to return timestamp of most recent pkgtree generation

### ISSUE THREAD

**Issue by eherget** [RedHatInsights/vmaas#412]
Possibly this could be implemented with the HEAD http request type, so -X HEAD .../api/v1/pkgtree would return the timestamp in a header.

**Comment by eherget** [comment]
When a Pull Request is created, please add jsvoboda to the watch list of the PR.

**Comment by tkasparek** [comment]
Let's add pkgtree export date to /dbchange API in the webapp.

**Comment by jdobes** [comment]
We decided to create new /dbchange API in the reposcan as pkgtree is kind of internal-only and not exposed in webapp so it's confusing for users to export the timestamp to different service.

**Comment by jdobes** [comment]
https://github.com/RedHatInsights/vmaas/pull/548
