### ISSUE TITLE
Teach vmaas to only consider the 'latest' EVR for any N that has multiple entries in /updates

### ISSUE THREAD

**Issue by tlestach** [RedHatInsights/vmaas#413]
Having multiple kernels installed:
\# rpm -q kernel
kernel-2.6.32-696.18.7.el6.x86_64
kernel-2.6.32-696.28.1.el6.x86_64
kernel-2.6.32-754.3.5.el6.x86_64
and passing the whole package list to VMaaS, I'm interested into updates of the latest kernel. Not into all, what is the current behavior.

(I'm aware the system may have booted a different kernel than the latest one, but make sure VmaaS works on the package level.)

**Comment by jdobes** [comment]
If you don't want to see vulnerabilities of given kernel version, don't send this kernel version in package list. This should be handled in app using vmaas. Closing.
