### ISSUE TITLE
reposcan /sync/pkgtree Swagger doc incorrect

### ISSUE THREAD

**Issue by ggainey** [RedHatInsights/vmaas#416]
Current doc has example-response of

```
{
  "success": true,
  "msg": "Repo sync task started."
}
```

Code actually reports

```
{
  "success": true,
  "msg": "Export package tree task started.."
}
```

**Comment by jdobes** [comment]
It's example string output for given schema, it doesn't make sense to have all possible string outputs in 2 places - doc and code. And it doesn't make sense to create second exactly same schema in openapi spec just to add other example value for the pkgtree endpoint.
