### ISSUE TITLE
repos not in vmaas - rhel-7-server-ose-3.10-rpms and rhel-7-server-ose-3.11-rpms

### ISSUE THREAD

**Issue by jsvob** [RedHatInsights/vmaas#430]
With a freshly downloaded (2018-11-22 12:20 UTC) pkgtree from `https://reposcan-vmaas-stage.1b13.insights.openshiftapps.com/api/v1/pkgtree` we found that there are no `atomic-openshift` versions from the `rhel-7-server-ose-3.10-rpms` and `rhel-7-server-ose-3.11-rpms repos`.

It looks like this is the newest repo in vmaas:

```
"label": "rhel-7-server-ose-3.9-rpms",
"name": "Red Hat OpenShift Container Platform 3.9 (RPMs)",
"arch": "x86_64",
```

But the 3.10 and 3.11 repos are not in vmaas.

Here is an output of our pulp-consuming script that shows versions and repos not in vmaas:

```
    'atomic-openshift-3.10.14-1.git.0.ba8ae6d.el7'   # repos: all-rpm-content, rhel-7-server-ose-3_DOT_10-rpms__x86_64, rhel-7-server-ose-3_DOT_10-source-rpms__x86_64 | last updated: 2018-07-30T18:59:08Z
    'atomic-openshift-3.10.34-1.git.0.4a94911.el7'   # repos: all-rpm-content, rhel-7-server-ose-3_DOT_10-rpms__x86_64, rhel-7-server-ose-3_DOT_10-source-rpms__x86_64 | last updated: 2018-08-31T06:09:19Z
    'atomic-openshift-3.10.45-1.git.0.3b98bf6.el7'   # repos: all-rpm-content, rhel-7-server-ose-3_DOT_10-rpms__x86_64, rhel-7-for-power-le-ose-3_DOT_10-source-rpms__ppc64le, rhel-7-for-power-le-ose-3_DOT_10-rpms__ppc64le, rhel-7-server-ose-3_DOT_10-source-rpms__x86_64 | last updated: 2018-09-20T15:23:06Z
    'atomic-openshift-3.10.66-1.git.0.91d1e89.el7'   # repos: all-rpm-content, rhel-7-server-ose-3_DOT_10-rpms__x86_64, rhel-7-for-power-le-ose-3_DOT_10-source-rpms__ppc64le, rhel-7-for-power-le-ose-3_DOT_10-rpms__ppc64le, rhel-7-server-ose-3_DOT_10-source-rpms__x86_64 | last updated: 2018-11-05T07:54:29Z
    'atomic-openshift-3.10.72-1.git.0.3cb2fdc.el7'   # repos: all-rpm-content, rhel-7-server-ose-3_DOT_10-rpms__x86_64, rhel-7-for-power-le-ose-3_DOT_10-source-rpms__ppc64le, rhel-7-for-power-le-ose-3_DOT_10-rpms__ppc64le, rhel-7-server-ose-3_DOT_10-source-rpms__x86_64 | last updated: 2018-11-17T12:17:37Z
    'atomic-openshift-3.11.16-1.git.0.b48b8f8.el7'   # repos: rhel-7-server-ose-3_DOT_11-rpms__x86_64, all-rpm-content, rhel-7-server-ose-3_DOT_11-source-rpms__x86_64 | last updated: 2018-10-10T10:33:02Z
    'atomic-openshift-3.11.43-1.git.0.647ac05.el7'   # repos: rhel-7-server-ose-3_DOT_11-rpms__x86_64, all-rpm-content, rhel-7-server-ose-3_DOT_11-source-rpms__x86_64 | last updated: 2018-11-19T12:49:57Z
```

I tried to cross-check the behavior and found another interesting thing - vmaas misses the latest versions from the latest repo that's in vmaas (3.9):
* is in vmaas - `curl -X GET "https://webapp-vmaas-stage.1b13.insights.openshiftapps.com/api/v1/packages/atomic-openshift-3.9.40-1.git.0.0c9824a.el7.x86_64" -H  "accept: application/json"`
* is not in vmaas - `curl -X GET "https://webapp-vmaas-stage.1b13.insights.openshiftapps.com/api/v1/packages/atomic-openshift-3.9.51-1.git.0.dc3a40b.el7.x86_64" -H  "accept: application/json"`

We found out about the missing versions&repos because we see systems that have installed NVRs vmaas is not aware of, but googling those NVRs led me back to Red Hat.

**Comment by jsvob** [comment]
What is the ETA on the repos rhel-7-server-ose-3.10-rpms and rhel-7-server-ose-3.11-rpms being added, please?

**Comment by ggainey** [comment]
-stage was a) missing repos, and b) had been failing to sync the repos it did know about due to being out of disk. I added the remaining -ose repos, re-sync'd, and reexported. Try again.

**Comment by jsvob** [comment]
It works now, thank you!

**Comment by ggainey** [comment]
ok - i'm going to close this issue then - thanks for rechecking!
