### ISSUE TITLE
Swagger doc uses example value as property name in definitions in several places...

### ISSUE THREAD

**Issue by eherget** [RedHatInsights/vmaas#435]
line 723 (cve), line 796 (repo), line 839 (errata), line 919 (package list), plus line 605 and 668.

Needs to be fixed to show that its returning a dictionary with keys that can be anything, and an example key is that shown in the lines above.

**Comment by jdobes** [comment]
fixed in webapp by https://github.com/RedHatInsights/vmaas/pull/436

still needs to be done in reposcan

**Comment by jdobes** [comment]
fixed in current master, closing
