### ISSUE TITLE
Store information about source packages

### ISSUE THREAD

**Issue by Allda** [RedHatInsights/vmaas#453]
Red Hat security metadata usually provides information about affected packages in one of these 2 formats.

* RPM packages (NEVRA - name-epoch:version-release.arch)
* Source packages (NEVR - name-epoch:version-release)
Unfortunately when a user uses multiple security data sources and each provides data in the different format it is always difficult to map package from one format to another.

It would be great if VMaaS could provide not only information about binary packages but also information about source packages.

**Comment by ggainey** [comment]
Minor nit - SRPM info in primary.xml is only NVR (for historical reasons that escape me at the moment)

The goal here would be to provide a /srpm API, which you could hand an SRPM NVR, and get back a list of the package NEVRAs that think they were built from from that SRPM - does that match your expectation?

**Comment by Allda** [comment]
I included epoch in source package because of the mapping file includes it as well.
https://www.redhat.com/security/data/metrics/cvemap.xml

But yeah, the general idea is to provide a mapping between rpm and srpm. You can provide another /srpm API, but it would be even better to include srpm in already created APIs (/advisory  or /cve or /packages) because in this case we could do simple API query instead several queries.

**Comment by tlestach** [comment]
@Allda, would you describe your use case, please?
What existing API would you need to add the srpm information? Is there any new API you'd need to introduce?

**Comment by Allda** [comment]
@tlestach We are currently using v1/errata/<advisory> API to get a list of rpms which are included in that advisory and then we have to map it to srpm using internal Red Hat's tools. It would be great if srpm information would be included in v1/errata/<advisory> so we can do mapping in just single call.

**Comment by jdobes** [comment]
@Allda We're preparing a new version providing SRPM mappings in all v1/errata, v1/cves and v1/packages APIs.

This is now deployed in stage environment, please check if these changes match your expectations.

https://apidoc-vmaas-stage.1b13.insights.openshiftapps.com

Example:
`curl -X GET "https://webapp-vmaas-stage.1b13.insights.openshiftapps.com/api/v1/errata/RHSA-2018:0512" -H  "accept: application/json"`
```
...
"source_package_list": [
    "kernel-2.6.32-696.23.1.el6.src"
],
...
```

**Comment by Allda** [comment]
@jdobes Thanks for example with included srpm, unfortunately with this output we are still not able to tell what it a relation between rpm and srpm. We would need a mapping between those 2 lists.

Something like:
```
srpm_mapping: {
  'srpm-1': [ rpm-XYZ, rpm-ABC ],
  'srpm-2': [ rpm-QWE, rpm-ZXC ],
  ...
}
```

Would you be able to provide this mapping?
Thank You

**Comment by Josca** [comment]
@Allda this mapping is provided with /packages endpoint, where you put source package as an input.

**Comment by Allda** [comment]
@Josca That's great! Thank you

**Comment by tlestach** [comment]
@Allda, can I take your last comment as a confirmation that the newly introduced API updates cover what you guys requested?

**Comment by Allda** [comment]
@tlestach yes, the new API update covers our use case.

**Comment by tlestach** [comment]
@Allda thank you!

**Comment by jdobes** [comment]
Requested functionality is in master, closing issue.
