### ISSUE TITLE
incorrect example of /v1/repos API in Swagger

### ISSUE THREAD

**Issue by tlestach** [RedHatInsights/vmaas#490]
On https://apidoc-vmaas-stable.1b13.insights.openshiftapps.com/#/repos/post_v1_repos
for POST /v1/repos
I see Example Value:
{
  "repository_list": [
    "rhel-6-server-rpms, rhel-7-server-rpms"
  ]
}

Note the quotation marks are not correct.
"rhel-6-server-rpms, rhel-7-server-rpms" vs "rhel-6-server-rpms", "rhel-7-server-rpms"

The same problem is visible also in the Curl command:
curl -X POST "https://webapp-vmaas-stable.1b13.insights.openshiftapps.com/api/v1/repos" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"repository_list\": [ \"rhel-6-server-rpms, rhel-7-server-rpms\" ]}"

that returns empty repository_list.
Again [ \"rhel-6-server-rpms, rhel-7-server-rpms\" ] vs [ \"rhel-6-server-rpms\", \"rhel-7-server-rpms\" ].

**Comment by jdobes** [comment]
fixed in current master, closing
