### ISSUE TITLE
api: improve input packages name parsing

### ISSUE THREAD

**Issue by grinrag** [RedHatInsights/vmaas#57]
Now we expect to have 'epoch' information as a first field in rpm-name `epoch:-name-version-release.arch`. 

We need to add possibility to pass rpm-name if format `name-:epoch-version-release.arch`

**Comment by grinrag** [comment]
After discussion, we decided to use *only* the second format:
`name-:epoch-version-release.arch` and in case if epoch is equal to `0`, just omit it.

**Comment by jdobes** [comment]
changed in #65
