### ISSUE TITLE
reposcan: wrong info about `epoch` in database

### ISSUE THREAD

**Issue by grinrag** [RedHatInsights/vmaas#60]
I paid my attention to one package which has been wrong parsed by the reposcan.

repository: server/7/7Server/x86_64/os/Packages/
package: texlive-soul-svn15878.2.4-32.el7.noarch.rpm

should be parsed as:
`epoch`: `0`
`name`: `texlive-soul`
`version`: `svn15878.2.4`
`release`: `32.el7`
`arch`: `noarch`

*BUT* in database I see:
id  | epoch |   version    | release |                                         evr                                          
------+-------+--------------+---------+--------------------------------------------------------------------------------------
 1340 | 2     | svn15878.2.4 | 32.el7  | (2,"{""(0,svn)"",""(15878,)"",""(2,)"",""(4,)""}","{""(32,)"",""(0,el)"",""(7,)""}")

**Comment by jdobes** [comment]
It should not be parsed with epoch 0. To get epoch included in installed package list use:

`rpm -qa --qf '%{EPOCHNUM}:%{NAME}-%{VERSION}-%{RELEASE}.%{ARCH}\n'`
