### ISSUE TITLE
webapp: if a sql error happens, webapp loses ability to talk to db

### ISSUE THREAD

**Issue by ggainey** [RedHatInsights/vmaas#67]
If the webapp ever causes a postgres error, it fails forever after due to

vmaas-webapp | InternalError: current transaction is aborted, commands ignored until end of transaction block

because Postgres requires an explicit rollback-on-error

**Comment by eherget** [comment]
This same error happens if you attempt to hit the updates api while reposcan is populating the db.  Then when reposcan is done, attempts to call the updates api continues to fail with the same message.

**Comment by eherget** [comment]
PR #125

**Comment by jdobes** [comment]
I can confirm this is fixed now. Closing.
